name: ci

on: [ push, pull_request ]

jobs:
  build-windows:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19.0.2
        uses: actions/setup-java@v3
        with:
          java-version: 19.0.2
          distribution: 'oracle'
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: PASSPHRASE
      - name: Build using script
        run: .\builders\windows.bat
      - name: Draft a release
        id: draft_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: true
          prerelease: false
      - name: List Files
        id: list_files
        run: |
          echo "::set-output name=files::$(ls .\build\releases\)"
      - name: Upload Release Assets
        id: upload_release_assets
        run: |
          @echo off
          (for %%file in (%steps.read_file_list.outputs.files%) do (
            echo "Uploading %%file"
            hub release edit --attach ".\build\releases\%%file" --prerelease=false "%steps.draft_release.outputs.upload_url%"
          ))