name: ci
on: [ push, pull_request ]
env:
  VERSION: 1.0.0
jobs:
  build-windows:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19.0.2
        uses: actions/setup-java@v3
        with:
          java-version: 19.0.2
          distribution: 'oracle'
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: PASSPHRASE
      - name: Build using script
        run: .\builders\windows.bat
      - name: Copy Artifacts to Workspace
        run: Copy-Item -Path build/releases/* -Destination ${{ github.workspace }}/build/releases -Force

  build-linux:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19.0.2
        uses: actions/setup-java@v3
        with:
          java-version: 19.0.2
          distribution: 'oracle'
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: PASSPHRASE

      - name: Install makeself
        run: sudo apt-get install makeself
      - name: Make script executable
        run: chmod +x ./builders/linux.sh
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build using script
        run: ./builders/linux.sh
      - name: Copy Artifacts to Workspace
        run: cp -R build/releases ${{ github.workspace }}/build/releases


  release-artifacts:
    runs-on: [ubuntu-latest]
    needs: [build-windows, build-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release Artifacts Directory
        run: mkdir build/releases
      - name: Copy Artifacts from Workspace
        run: cp -R ${{ github.workspace }}/build/releases/* build/releases
      - name: ls tree
        run: tree .
      - name: Release Artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          automatic_release_tag: "v${{ env.VERSION }}"
          prerelease: false
          draft: true
          title: "v${{ env.VERSION }}"
          files: |
            ./build/releases/**
