name: ci

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19.0.2
        uses: actions/setup-java@v3
        with:
          java-version: 19.0.2
          distribution: 'oracle'
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: PASSPHRASE
      - name: Build with Gradle
        run: ./gradlew.bat build
        env:
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Create Distribution
        run: .\builders\windows.bat
      - uses: actions/upload-artifact@v3
        with:
          name: Actions demo
          path: build/releases
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            
            This is an automated release generated by the CI workflow.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/releases/*
          asset_name: Asset.zip
          asset_content_type: application/zip